App/App/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Models;

namespace App.Controllers
{
    public class ImageController : Controller
    {
        DB_TESTEntities db = new Models.DB_TESTEntities();
        // GET: Image
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult addnewrecord()
        {
            ViewBag.Message = "Yout contact Page";
            return View();
        }
        [HttpPost]
        public ActionResult addnewrecord(tbl_data d,HttpPostedFileBase imgfile)
        {
            tbl_data di = new tbl_data();
            string path = uploadimage(imgfile);

            if (path.Equals("-1"))
            {

            }
            else
            {
                di.P_name = d.P_name;
                di.P_DES = d.P_DES;
                di.P_IMAGE = d.P_IMAGE;
                db.tbl_data.Add(di);
                db.SaveChanges();
                ViewBag.Message = "Data added....";
            }
            return View();
        }
        public string uploadimage(HttpPostedFileBase file)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (file != null && file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {
                    try
                    {
                        path = Path.Combine(Server.MapPath("~/Content/upload"), random + Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        path = "~/Content/upload" + random + Path.GetFileName(file.FileName);
                    }
                    catch (Exception e )
                    {

                        path = "-1" + e.ToString();
                    }

                }
                else
                {
                    Response.Write("<script>alert('Please select a file');</script>");
                    path = "-1";
                }
            }
            return path;
        }
    }
}

App/App/Views/Image/addnewrecord.cshtml
@model App.Models.tbl_data

@{
    ViewBag.Title = "addnewrecord";
}

<h1>
    @ViewBag.Message
</h1>

<h2>addnewrecord</h2>


@using (Html.BeginForm("addnewrecord","Image",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.P_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_DES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_DES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_DES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @* @Html.EditorFor(model => model.P_IMAGE, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" id="imgfile" name="imgfile" class="btn btn-info"/>
                @Html.ValidationMessageFor(model => model.P_IMAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}