App/App/Controllers/ComprasController.cs
using App.Models;
using App.Models.ViewModels;
using Microsoft.AspNetCore.Http.Features;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App.Controllers
{
    public class ComprasController : Controller
    {
        dbAppEntities1 db = new dbAppEntities1();
        // GET: Compras
        public ActionResult Index()
        {
            List<FacturaViewModel> model ;
            var message = "";
            try
            {
                model  = (from fs in db.Facturas
                              select new FacturaViewModel { 
                                Id = fs.Id,
                                Total = fs.Total,
                                FechaCompra = fs.FechaCompra
                              }).ToList();

                message = "success";
            }
            catch (Exception e)
            {
                message = "fail: " + e.StackTrace;
                throw;
            }            

            return View(model);
        }

        public ActionResult Nuevo()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(FacturaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var oFactura = new Factura(){ 
                        Total = model.Total,
                        FechaCompra = model.FechaCompra
                    };

                    db.Facturas.Add(oFactura);
                    db.SaveChanges();

                    return Redirect("~/Compras");
                }

                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        public ActionResult Edit(int Id)
        {
            
            
                var oFactura = db.Facturas.Find(Id);

            FacturaViewModel model = new FacturaViewModel()
            {
                Total = oFactura.Total,
                FechaCompra = oFactura.FechaCompra,
                Id = oFactura.Id
            };
            

             return View(model);

        }

        [HttpPost]
        public ActionResult Edit(FacturaViewModel model)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var oFactura = db.Facturas.Find(model.Id);
                    oFactura.Total = model.Total;
                    oFactura.FechaCompra = model.FechaCompra;

                    db.Entry(oFactura).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();

                    return Redirect("~/Compras");
                }

                return View(model);
            }
            catch (Exception e)
            {

                throw;
            }
        }

        public ActionResult Delete(int Id)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var oFactura = db.Facturas.Find(Id);
                    db.Facturas.Remove(oFactura);
                    db.SaveChanges();

                    return Redirect("~/Compras");
                }
            }
            catch (Exception e)
            {

                throw;
            }

            return Redirect("~/Compras");
        }
    }
}

App/App/Views/Compras/Edit.cshtml
@model App.Models.ViewModels.FacturaViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Compras", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(x => x.Id)
            <div>
                @Html.LabelFor(x => x.Total)
                @Html.TextBoxFor(x => x.Total, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Total, null, new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.FechaCompra)
                @Html.EditorFor(x => x.FechaCompra, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.FechaCompra, null, new { @class = "text-danger" })
            </div>
            <br />
            <div>
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>

        </div>
    </div>
}

App/App/Views/Compras/Index.cshtml
@model List<App.Models.ViewModels.FacturaViewModel>
@{
    ViewBag.Title = "GuardarFactura";
}

<h2>GuardarFactura</h2>

<a href="~/Compras/Nuevo" class="btn btn-primary">Nuevo</a>
@using (Html.BeginForm("AgregarFactura", "Compras", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">

            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Total</td>
                        <td>@item.FechaCompra</td>
                        <td>
                            <a class="btn btn-default" href="~/Compras/Edit/@item.Id">Edit</a>
                            <a class="btn btn-danger" href="~/Compras/Delete/@item.Id">Delete</a>
                        </td>   
                    </tr>
                    }
                    
                </tbody>
            </table>

        </div>
    </div>
}

App/App/Views/Compras/Nuevo.cshtml
@model App.Models.ViewModels.FacturaViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>GuardarFactura</h2>

@using (Html.BeginForm("Nuevo", "Compras", FormMethod.Post)){
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(x => x.Total)
                @Html.TextBoxFor(x => x.Total, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Total, null, new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.FechaCompra)
                @Html.EditorFor(x => x.FechaCompra, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.FechaCompra, null, new { @class="text-danger" })
            </div>
                <br />
            <div>
                <input type="submit"  value="Guardar" class="btn btn-primary" />
            </div>

        </div>
    </div>
}